      /// !------------ CAUTION ------------!
      /// Autogenerated file. Please do not edit it manually!
      /// Updated: 2021-04-24 04:17:55.345036
      /// !---------- END CAUTION ----------!

      
 final useIDsState = Provider<ID>((_)=>
  CactusStateModel<ID>()
);


 final useTodosState = Provider<Todo>((_)=>
  CactusStateModel<Todo>()
);


 final useUsersState = Provider<User>((_)=>
  CactusStateModel<User>()
);


 final useCactusSyncTimestampsState = Provider<CactusSyncTimestamp>((_)=>
  CactusStateModel<CactusSyncTimestamp>()
);


 final useDatabaseChangeTypesState = Provider<DatabaseChangeType>((_)=>
  CactusStateModel<DatabaseChangeType>()
);


    